import type { Metadata } from "next";
import { Geist, Geist_Mono ,Oswald } from "next/font/google";
import "./globals.css";
import Navbar from "@/Components/Shared/Navbar";
import ContextApi from "@/Context/ContextApi";
import Footer from "@/Components/Shared/Footer";
import { ToastContainer } from "react-toastify";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

const oswald = Oswald({
  subsets: ['latin'],
  variable: '--font-oswald',
  display: 'swap',
})
export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }: LayoutProps<"/">) {
  return (
    <html
      lang="en"
      className={`${geistSans.variable} ${geistMono.variable } ${oswald.variable} h-full antialiased`}
    >
      <body className="min-h-full flex flex-col">
         <ContextApi>
          <Navbar></Navbar>
          {children}
          <ToastContainer />
          <Footer></Footer>
         </ContextApi>
        
        </body>
    </html>
  );
}
